books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 300,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "author": "Antonio Melé",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2022-01-19",
        "page_count": 420,
        "language": "English",
    },
    {
        "id": 3,
        "title": "The WebSocket Handbook",
        "author": "Alex Diaconu",
        "publisher": "Practical Guides",
        "published_date": "2021-01-01",
        "page_count": 240,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2015-08-20",
        "page_count": 792,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Clean Code in Python",
        "author": "Mariano Anaya",
        "publisher": "Packt Publishing",
        "published_date": "2018-08-29",
        "page_count": 330,
        "language": "English",
    },
]